// Mock data for development
import type { User, HotelRoom, TaxiService, Pet, CityPricing, RoomPricing, SharedTaxiSchedule } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "user@example.com",
    name: "Ahmet Yılmaz",
    phone: "+905551234567",
    passwordHash: "hashed_password_123",
    role: "user",
    emailVerified: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "admin-1",
    email: "admin@petfendy.com",
    name: "Admin User",
    phone: "+905559876543",
    passwordHash: "hashed_admin_password",
    role: "admin",
    emailVerified: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockHotelRooms: HotelRoom[] = [
  {
    id: "room-1",
    name: "Standart Oda",
    type: "standard",
    capacity: 1,
    pricePerNight: 150,
    available: true,
    amenities: ["Yatak", "Su Kasesi", "Oyuncaklar"],
  },
  {
    id: "room-2",
    name: "Deluxe Oda",
    type: "deluxe",
    capacity: 2,
    pricePerNight: 250,
    available: true,
    amenities: ["Yatak", "Oyun Alanı", "Kamera Gözetimi", "Klima"],
  },
  {
    id: "room-3",
    name: "Suite Oda",
    type: "suite",
    capacity: 3,
    pricePerNight: 400,
    available: true,
    amenities: ["Geniş Yatak", "Özel Oyun Alanı", "24/7 Kamera", "Klima", "Isıtma"],
  },
]

export const mockTaxiServices: TaxiService[] = [
  {
    id: "taxi-1",
    name: "VIP Pet Taxi",
    description: "Özel evcil hayvan taşıma servisi - Sadece sizin için",
    basePrice: 100,
    pricePerKm: 20,
    maxPetWeight: 15,
    capacity: 1,
    features: ["Özel araç", "Klima", "GPS takip", "Deneyimli şoför"],
    available: true,
    taxiType: "vip",
  },
  {
    id: "taxi-2",
    name: "VIP Luxury Pet Transport",
    description: "Premium araçlarla lüks evcil hayvan taşıma hizmeti",
    basePrice: 150,
    pricePerKm: 30,
    maxPetWeight: 25,
    capacity: 2,
    features: ["Premium araç", "Veteriner refakat", "GPS takip", "Özel bakım", "Su ve mama servisi"],
    available: true,
    taxiType: "vip",
  },
  {
    id: "taxi-3",
    name: "Paylaşımlı Pet Taxi",
    description: "Ekonomik paylaşımlı evcil hayvan taşıma servisi - Programlı seferler",
    basePrice: 0,
    pricePerKm: 0,
    maxPetWeight: 10,
    capacity: 4,
    features: ["Ekonomik", "Güvenli taşıma", "Programlı seferler", "Klima"],
    available: true,
    taxiType: "shared",
  },
]

export const mockPets: Pet[] = [
  {
    id: "pet-1",
    userId: "1",
    name: "Boncuk",
    type: "dog",
    breed: "Golden Retriever",
    age: 3,
    weight: 25,
    specialNeeds: "Hiçbiri",
  },
  {
    id: "pet-2",
    userId: "1",
    name: "Misi",
    type: "cat",
    breed: "Siamese",
    age: 2,
    weight: 4,
    specialNeeds: "Diyetli mama",
  },
]

// City-based pricing for taxi service
export const mockCityPricings: CityPricing[] = [
  {
    id: "city-1",
    fromCity: "İstanbul",
    toCity: "Ankara",
    additionalFee: 100,
    discount: 0,
    distanceKm: 450,
  },
  {
    id: "city-2",
    fromCity: "İstanbul",
    toCity: "İzmir",
    additionalFee: 150,
    discount: 10,
    distanceKm: 470,
  },
  {
    id: "city-3",
    fromCity: "Ankara",
    toCity: "İzmir",
    additionalFee: 80,
    discount: 0,
    distanceKm: 590,
  },
]

// Room pricing for dynamic date-based pricing
export const mockRoomPricings: RoomPricing[] = [
  {
    id: "price-1",
    roomId: "room-1",
    date: new Date("2025-12-31"),
    pricePerNight: 250,
    available: true,
  },
  {
    id: "price-2",
    roomId: "room-2",
    date: new Date("2025-12-31"),
    pricePerNight: 400,
    available: true,
  },
]

// Turkish cities for taxi service
export const mockTurkishCities = [
  "İstanbul",
  "Ankara",
  "İzmir",
  "Bursa",
  "Antalya",
  "Adana",
  "Konya",
  "Gaziantep",
  "Şanlıurfa",
  "Kocaeli",
  "Mersin",
  "Diyarbakır",
  "Hatay",
  "Manisa",
  "Kayseri",
]

// Paylaşımlı taksi programları - Seyahat tarihleri ve müsaitlik
export const mockSharedTaxiSchedules: SharedTaxiSchedule[] = [
  // İstanbul -> Ankara seferleri
  {
    id: "schedule-1",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "Ankara",
    travelDate: new Date("2025-11-10"),
    maxCapacity: 4,
    bookedCount: 1,
    pricePerSeat: 300,
    departureTime: "09:00",
    status: "active",
  },
  {
    id: "schedule-2",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "Ankara",
    travelDate: new Date("2025-11-12"),
    maxCapacity: 4,
    bookedCount: 2,
    pricePerSeat: 300,
    departureTime: "14:00",
    status: "active",
  },
  {
    id: "schedule-3",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "Ankara",
    travelDate: new Date("2025-11-15"),
    maxCapacity: 4,
    bookedCount: 4,
    pricePerSeat: 300,
    departureTime: "10:00",
    status: "full",
  },
  {
    id: "schedule-4",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "Ankara",
    travelDate: new Date("2025-11-18"),
    maxCapacity: 4,
    bookedCount: 0,
    pricePerSeat: 300,
    departureTime: "09:00",
    status: "active",
  },
  {
    id: "schedule-5",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "Ankara",
    travelDate: new Date("2025-11-20"),
    maxCapacity: 4,
    bookedCount: 3,
    pricePerSeat: 300,
    departureTime: "15:00",
    status: "active",
  },
  // İstanbul -> İzmir seferleri
  {
    id: "schedule-6",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "İzmir",
    travelDate: new Date("2025-11-11"),
    maxCapacity: 4,
    bookedCount: 1,
    pricePerSeat: 350,
    departureTime: "08:00",
    status: "active",
  },
  {
    id: "schedule-7",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "İzmir",
    travelDate: new Date("2025-11-14"),
    maxCapacity: 4,
    bookedCount: 0,
    pricePerSeat: 350,
    departureTime: "10:00",
    status: "active",
  },
  {
    id: "schedule-8",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "İzmir",
    travelDate: new Date("2025-11-17"),
    maxCapacity: 4,
    bookedCount: 4,
    pricePerSeat: 350,
    departureTime: "09:00",
    status: "full",
  },
  {
    id: "schedule-9",
    taxiServiceId: "taxi-3",
    fromCity: "İstanbul",
    toCity: "İzmir",
    travelDate: new Date("2025-11-21"),
    maxCapacity: 4,
    bookedCount: 2,
    pricePerSeat: 350,
    departureTime: "11:00",
    status: "active",
  },
  // Ankara -> İzmir seferleri
  {
    id: "schedule-10",
    taxiServiceId: "taxi-3",
    fromCity: "Ankara",
    toCity: "İzmir",
    travelDate: new Date("2025-11-13"),
    maxCapacity: 4,
    bookedCount: 1,
    pricePerSeat: 400,
    departureTime: "09:30",
    status: "active",
  },
  {
    id: "schedule-11",
    taxiServiceId: "taxi-3",
    fromCity: "Ankara",
    toCity: "İzmir",
    travelDate: new Date("2025-11-16"),
    maxCapacity: 4,
    bookedCount: 3,
    pricePerSeat: 400,
    departureTime: "14:00",
    status: "active",
  },
  {
    id: "schedule-12",
    taxiServiceId: "taxi-3",
    fromCity: "Ankara",
    toCity: "İzmir",
    travelDate: new Date("2025-11-19"),
    maxCapacity: 4,
    bookedCount: 0,
    pricePerSeat: 400,
    departureTime: "10:00",
    status: "active",
  },
]
